version: "3.9"

services:
  # mongodb:
  #   image: prismagraphql/mongo-single-replica:5.0.3
  #   container_name: mongodb
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ggwp
  #     MONGO_INITDB_ROOT_PASSWORD: 5nP0eh1Gis9697aGGWPLR8p16mglbFTzuOhsn8oz6P3Qhij
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data/mongo:/data/db
  #   restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5nP0eh1Gis9697aGGWPLR8p16mglbFTzuOhsn8oz6P3Qklkjsd
      MYSQL_USER: ggwp
      MYSQL_PASSWORD: ggwp
    restart: always
    ports:
      - "3192:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 512M
    restart: always
    ports:
      - 4192:80

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass 5nP0eh1Gis9697aGGWPLR8p16mglbFTzuOhsn8oz6P3Qsslkj323jk
    ports:
      - 5192:6379
    volumes:
      - ./data/redis:/data
